services:
  noun-gender:
    image: ghcr.io/kako-jun/noun-gender:latest
    expose:
      - "3002"
    restart: unless-stopped
    container_name: noun-gender-app
    environment:
      - NODE_ENV=production
    networks:
      - proxy-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3002/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  proxy-network:
    external: true